name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Zig binary
        run: wget https://ziglang.org/download/0.14.0/zig-linux-x86_64-0.14.0.tar.xz

      - name: Extract Zig
        run: tar -xf zig-linux-x86_64-0.14.0.tar.xz

      - name: Add Zig to PATH
        run: echo "$PWD/zig-linux-x86_64-0.14.0" >> $GITHUB_PATH

      - name: Verify Zig version
        run: zig version

      - name: Build the project
        run: zig build
