name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0

      - name: Build Project
        run: zig build

      - name: Run tests
        run: zig build test
